# https://squidfunk.github.io/mkdocs-material/setup/
site_name: LaboInfra Docs
site_author: LaboInfra ESGI
site_description: >-
  Documentation for LaboInfra projects.
site_url: https://docs.laboinfra.net

repo_name: laboinfra.github.io
repo_url: https://github.com/LaboInfra/laboinfra.github.io
edit_uri: edit/main/docs/
copyright: >
  Copyright &copy; 2022 - 2025 LaboInfra ESGI –
  <a href="#__consent">Change cookie settings</a>

nav:
  - Projects:
    - Overview: index.md
    - Cloud: project/cloud.md
    - Game: project/game.md
    - MindBreak: project/mindbreak.md
  - Cloud:
    - Getting started: cloud/getting-started.md
    - Install certificate: cloud/cert.md
    - CLI reference: cloud/cli.md
    - Terms of service: cloud/tos.md
  - Game:
    - game/index.md
  - Team: team.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md
  - Join us: join.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - social
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - git-committers:
      repository: LaboInfra/laboinfra.github.io
      branch: main

extra:
  logo: assets/images/logo.png
  favicon: assets/favicon.png
  homepage: https://docs.laboinfra.net
  generator: true
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/9GtVSvfUZ4
    - icon: fontawesome/brands/github
      link: https://github.com/LaboInfra
    - icon: fontawesome/solid/paper-plane
      link: mailto:contact@laboinfra.net
  consent:
    actions:
      - manage
      - reject
      - accept
    title: Cookie consent
    description: >-
      We use cookies to display GitHub stats on the docs and because this site is hosted on GitHub Pages.
      By consenting, you help us improve our services and provide a better experience.

theme:
  font: false
  name: material
  language: en
  direction: ltr
  logo: assets/images/logo.png
  favicon: assets/images/logo.png

  icon:
    repo: fontawesome/brands/git-alt

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.prune
    - navigation.indexes
    - navigation.top

    - toc.follow

    - search.suggest
    - search.highlight
    - search.share

    - content.action.edit
    - content.code.copy

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: light blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: light blue
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: light blue
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
